[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "muddoc"
authors = [{name = "Sanbao", email = "zsanbao@gmail.com"}]
dynamic = ["version", "description"]
